name: Test workflow template 2

on:
  push:
    branches: [ $default-branch ]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello this is another workflow template"
